### PR TITLE
Allow to download directly to target machine

### PR DESCRIPTION
**Pull request by t2d**
Keep current behavior as default

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
Rather download into `~/Downloads` so that can be used as cache, instead of /tmp (where anyone can prank you)

**Comment by t2d** [comment]
Downloading to `/tmp` is the default behavior of your role. Do you want me to change it?

**Comment by bbaassssiiee** [comment]
No, that's OK.

**Comment by t2d** [comment]
Somehow the test is stuck and blocking a merge. Can you please cancel or restart?

**Pull request merged**
