### PR TITLE
Show only failing tests

### PR DESCRIPTION
**Pull request by t2d**
This pull request fixes  `goss_format=json` in order to allow to search the test results for test that have failed. It only shows failed tests then.

A failing output will look like this:
```
TASK [dockpack.base_goss : Execute Goss tests] ******************************************************
ok: [host.example.org]

TASK [dockpack.base_goss : Show failing Goss tests] *************************************************
failed: [host.example.org] (item=File: /usr/local/bin/goss: owner:
Expected
    <string>: ansible
to equal
    <string>: root) => {
    "msg": "Goss test failed"
}
fatal: [host.example.org]: FAILED! => {"msg": "All items completed"}

PLAY RECAP ******************************************************************************************
host.example.org        : ok=3    changed=0    unreachable=0    failed=1
```

Good output will look like this:
```
TASK [dockpack.base_goss : Execute Goss tests] ******************************************************
ok: [host.example.org]

TASK [dockpack.base_goss : Show failing Goss tests] *************************************************

PLAY RECAP ******************************************************************************************
host.example.org        : ok=3    changed=0    unreachable=0    failed=0
```

I believe this output is much more actionable then before.

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
You need to install "jmespath" prior to running json_query filter", on travis, and as dependency too?

**Comment by t2d** [comment]
Thank you I adjusted `README.md` and `requirements.yml`.

**Comment by bbaassssiiee** [comment]
Commits are moved to PR 17

**Comment by bbaassssiiee** [comment]
Build failure in dependent role due to jmespath not being installed.

https://travis-ci.org/dockpack/base_java8/builds/552517512?utm_medium=notification&utm_source=email

**Pull request closed without merging**
